alias: Send Neptune Max Printer Progress to Discord & Alexa (Moonraker)
description: monkies code better than AI.
triggers:
  - entity_id: sensor.neptune_max_current_print_state
    from:
      - idle
      - standby
      - completed
      - error
    to: printing
    id: started
    trigger: state
  - entity_id: sensor.neptune_max_current_print_state
    from: paused
    to: printing
    id: resumed
    trigger: state
  - entity_id: sensor.neptune_max_progress
    id: progress
    trigger: state
  - entity_id: sensor.neptune_max_current_print_state
    from: printing
    to:
      - idle
      - standby
      - completed
      - error
    id: finished
    trigger: state
  - entity_id: sensor.neptune_max_current_print_state
    to: paused
    id: paused
    trigger: state
conditions:
  - condition: or
    conditions:
      - condition: trigger
        id: started
      - condition: trigger
        id: resumed
      - condition: trigger
        id: finished
      - condition: trigger
        id: paused
      - condition: template
        value_template: >
          {{ trigger.to_state.state | float % 5 == 0 and trigger.to_state.state
          | float > 0 and trigger.id == 'progress' }}
  - condition: template
    value_template: |
      {% if trigger.id == 'started' %}
        {{ not is_state('sensor.neptune_max_current_print_state', 'paused') }}
      {% else %}
        true
      {% endif %}
actions:
  - delay: "00:00:01"
  - target:
      entity_id: |
        {% if trigger.id == 'started' %}
          camera.neptune_max_thumbnail
        {% else %}
          camera.neptune_max_webcam
        {% endif %}
    data:
      filename: /config/www/3dprinter_snapshot.jpg
    action: camera.snapshot
  - delay: "00:00:02"
  - data_template:
      message: |-
        {% if trigger.id == 'paused' %}
          ⏸️ Print Job Paused!
        {% elif trigger.id == 'resumed' %}
          🔄 Print Job Resumed!
        {% elif trigger.id == 'started' %}
          🖨️ Print Job Started! 📄 File: {{ states('sensor.neptune_max_filename') }}
        {% elif trigger.id == "progress" %}
          📢 Printing is at {{ states('sensor.neptune_max_progress') | round(0) }}% ETA: {% set total_minutes = (states('sensor.neptune_max_print_time_left') | float * 60) | round %}{% set hours = total_minutes // 60 %}{% set minutes = total_minutes % 60 %}{{ hours }}h {{ minutes }}m | Layer: {{ states('sensor.neptune_max_current_layer') }}/{{ states('sensor.neptune_max_total_layer') }}
        {% elif trigger.id == 'finished' %}
          ✅ Print Job Completed! 🧵 Total Filament Used: {{ states('sensor.neptune_max_totals_filament_used') }}m ({{ (states('sensor.neptune_max_totals_filament_used') | float * 0.000621371) | round(2) }} mi) ⏱️ Total Time: {{ states('sensor.neptune_max_totals_print_time') }}
        {% endif %}
    action: shell_command.printer_notify_webhook
  - choose:
      - conditions:
          - condition: time
            after: "09:00:00"
            before: "23:59:00"
        sequence:
          - data:
              message: |-
                {% if trigger.id == 'paused' %}
                  Print job paused.
                {% elif trigger.id == 'resumed' %}
                  Print job resumed.
                {% elif trigger.id == 'started' %}
                  Print job started.
                {% elif trigger.id == 'finished' %}
                  Print job completed on Neptune 4.
                {% endif %}
              data:
                type: announce
            action: notify.alexa_media_echoclockdot
mode: queued
max: 10
